# Generated by Django 5.2.8 on 2025-11-15 00:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
            ],
            options={
                'db_table': 'caja',
                'permissions': [('can_open_caja', 'Puede abrir caja'), ('can_close_caja', 'Puede cerrar caja'), ('can_view_caja', 'Puede ver caja')],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo_cuenta_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoNegocio',
            fields=[
                ('id_negocio', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Negocio',
                'verbose_name_plural': 'Tipos de Negocio',
                'db_table': 'tipo_negocio',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='CajaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthenasApp.caja')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCorrienteCliente',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateField(default=django.utils.timezone.now)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.clientes')),
                ('negocio', models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente de Cliente',
                'verbose_name_plural': 'Cuentas Corrientes de Clientes',
                'db_table': 'cuentas_corrientes_clientes',
                'permissions': [('can_view_cuentas_corrientes', 'Puede ver cuentas corrientes')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caja_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthenasApp.cajausuario')),
            ],
            options={
                'db_table': 'movimientos_caja',
            },
        ),
        migrations.CreateModel(
            name='PagoClientes',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.clientes')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'db_table': 'pago_clientes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margen_ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AthenasApp.categoria')),
                ('marca', models.ForeignKey(blank=True, db_column='id_marca', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AthenasApp.marca')),
                ('negocio', models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio')),
                ('unidad', models.ForeignKey(blank=True, db_column='id_unidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AthenasApp.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AthenasApp.tiponegocio')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'perfil_usuario',
                'permissions': [('can_switch_negocio', 'Puede cambiar/seleccionar el negocio actual')],
            },
        ),
        migrations.AddField(
            model_name='marca',
            name='negocio',
            field=models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio'),
        ),
        migrations.CreateModel(
            name='ConfiguracionCredito',
            fields=[
                ('id_config_credito', models.AutoField(primary_key=True, serialize=False)),
                ('limite_por_defecto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_mora', models.PositiveIntegerField(default=0)),
                ('interes_mora', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio')),
            ],
            options={
                'verbose_name': 'Configuración de Crédito',
                'verbose_name_plural': 'Configuraciones de Crédito',
                'db_table': 'configuracion_credito',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='negocio',
            field=models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio', verbose_name='Negocio'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='negocio',
            field=models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio'),
        ),
        migrations.AddField(
            model_name='caja',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('negocio', models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio', verbose_name='Negocio')),
                ('rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='RespaldoSistema',
            fields=[
                ('id_respaldo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_respaldo', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='respaldos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('exito', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Respaldo del Sistema',
                'verbose_name_plural': 'Respaldos del Sistema',
                'db_table': 'respaldos_sistema',
                'ordering': ['-fecha_respaldo'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSistema',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('VENTAS', 'Reporte de Ventas'), ('COMPRAS', 'Reporte de Compras'), ('STOCK', 'Reporte de Stock'), ('CLIENTES', 'Reporte de Clientes'), ('PROVEEDORES', 'Reporte de Proveedores'), ('CAJA', 'Reporte de Caja'), ('GENERAL', 'Reporte General')], default='GENERAL', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/')),
                ('grafico', models.ImageField(blank=True, null=True, upload_to='reportes/graficos/%Y/%m/')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Reporte del Sistema',
                'verbose_name_plural': 'Reportes del Sistema',
                'db_table': 'reportes_sistema',
                'ordering': ['-generado_en'],
                'permissions': [('can_view_reportes', 'Puede ver reportes del sistema')],
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaCorriente',
            fields=[
                ('id_pago_cc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='AthenasApp.cuentacorrientecliente')),
                ('usuario_registra', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Pago de Cuenta Corriente',
                'verbose_name_plural': 'Pagos de Cuentas Corrientes',
                'db_table': 'pagos_cuenta_corriente',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('ANULACIÓN', 'Anulación')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.productos')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.usuarios')),
            ],
            options={
                'db_table': 'movimientos_stock',
                'permissions': [('can_adjust_stock', 'Puede ajustar stock')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuentaCorriente',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('CARGO', 'Cargo por venta a crédito'), ('ABONO', 'Pago o ajuste')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='AthenasApp.cuentacorrientecliente')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta Corriente',
                'verbose_name_plural': 'Movimientos de Cuenta Corriente',
                'db_table': 'movimientos_cuenta_corriente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(max_length=100)),
                ('entidad_afectada', models.CharField(max_length=50)),
                ('id_registro', models.PositiveIntegerField()),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'log_auditoria',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.proveedores')),
                ('negocio', models.ForeignKey(blank=True, db_column='id_negocio', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio', verbose_name='Negocio')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compras_creadas', to='AthenasApp.usuarios')),
                ('usuario_actualiza', models.ForeignKey(blank=True, db_column='id_usuario_actualiza', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compras_actualizadas', to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha', '-id_compra'],
                'permissions': [('can_confirm_purchase', 'Puede confirmar compras'), ('can_cancel_purchase', 'Puede anular compras')],
            },
        ),
        migrations.AddField(
            model_name='cajausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.usuarios'),
        ),
        migrations.CreateModel(
            name='BitacoraSistema',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=150)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('exito', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Bitácora del Sistema',
                'verbose_name_plural': 'Bitácoras del Sistema',
                'db_table': 'bitacora_sistema',
                'ordering': ['-fecha'],
                'permissions': [('can_view_bitacora', 'Puede ver bitácora del sistema')],
            },
        ),
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('STOCK', 'Stock Bajo'), ('VENCIMIENTO', 'Producto Vencido / Próximo a Vencer'), ('MORA', 'Cliente en Mora'), ('CAJA', 'Irregularidad en Caja'), ('GENERAL', 'Aviso General')], default='GENERAL', max_length=20)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('mensaje', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.tiponegocio')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'db_table': 'alertas_sistema',
                'ordering': ['-creado_en'],
                'permissions': [('can_view_alertas', 'Puede ver alertas del sistema')],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField(editable=False)),
                ('nro_secuencial', models.PositiveIntegerField(editable=False)),
                ('numero_ticket', models.CharField(editable=False, max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_global_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(blank=True, db_column='id_caja', null=True, on_delete=django.db.models.deletion.PROTECT, to='AthenasApp.caja')),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, to='AthenasApp.clientes')),
                ('negocio', models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.PROTECT, to='AthenasApp.tiponegocio', verbose_name='Negocio')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='AthenasApp.usuarios')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha', '-id_venta'],
                'permissions': [('can_confirm_sale', 'Puede confirmar ventas'), ('cancel_venta', 'Puede anular ventas')],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=120)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_item_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='AthenasApp.productos')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AthenasApp.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalle_ventas',
            },
        ),
        migrations.CreateModel(
            name='VentaPago',
            fields=[
                ('id_pago_venta', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='AthenasApp.venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'pago_ventas',
            },
        ),
        migrations.CreateModel(
            name='ComprobantesCompra',
            fields=[
                ('id_comprobante_compra', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='compras/comprobantes/%Y/%m/')),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_compra', to='AthenasApp.compras')),
            ],
            options={
                'verbose_name': 'Comprobante de Compra',
                'verbose_name_plural': 'Comprobantes de Compra',
                'db_table': 'comprobantes_compra',
                'indexes': [models.Index(fields=['compra'], name='comprobante_id_comp_a10350_idx'), models.Index(fields=['tipo', 'numero'], name='comprobante_tipo_104ace_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstadoMorosidad',
            fields=[
                ('id_estado_mora', models.AutoField(primary_key=True, serialize=False)),
                ('en_mora', models.BooleanField(default=False)),
                ('fecha_inicio_mora', models.DateField(blank=True, null=True)),
                ('fecha_fin_mora', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.clientes')),
            ],
            options={
                'verbose_name': 'Estado de Morosidad',
                'verbose_name_plural': 'Estados de Morosidad',
                'db_table': 'estado_morosidad',
                'indexes': [models.Index(fields=['cliente'], name='estado_moro_id_clie_531118_idx'), models.Index(fields=['en_mora'], name='estado_moro_en_mora_6e0bd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compras', to='AthenasApp.compras')),
                ('producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AthenasApp.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'detalle_compras',
                'indexes': [models.Index(fields=['compra'], name='detalle_com_id_comp_7b574f_idx'), models.Index(fields=['producto'], name='detalle_com_id_prod_8e8198_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_asociados', to='AthenasApp.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_asociados', to='AthenasApp.proveedores')),
            ],
            options={
                'verbose_name': 'Relación Proveedor–Producto',
                'verbose_name_plural': 'Relaciones Proveedor–Producto',
                'db_table': 'proveedor_producto',
                'unique_together': {('proveedor', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ParametroReporte',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=200)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='AthenasApp.reportesistema')),
            ],
            options={
                'verbose_name': 'Parámetro de Reporte',
                'verbose_name_plural': 'Parámetros de Reporte',
                'db_table': 'parametros_reporte',
                'indexes': [models.Index(fields=['reporte'], name='parametros__reporte_da2def_idx'), models.Index(fields=['clave'], name='parametros__clave_303a7a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='proveedores',
            index=models.Index(fields=['negocio', 'razon_social'], name='proveedores_id_nego_8cb255_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedores',
            index=models.Index(fields=['negocio', 'cuit'], name='proveedores_id_nego_3420c7_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedores',
            index=models.Index(fields=['negocio', 'activo'], name='proveedores_id_nego_b6d157_idx'),
        ),
        migrations.AddConstraint(
            model_name='proveedores',
            constraint=models.UniqueConstraint(fields=('negocio', 'cuit'), name='uniq_proveedor_cuit_por_negocio'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['negocio', 'nombre'], name='marcas_id_nego_5da8ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('negocio', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['cliente'], name='cuentas_cor_id_clie_b25ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['negocio'], name='cuentas_cor_id_nego_ecb071_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['activo'], name='cuentas_cor_activo_e107db_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['negocio', 'nombre'], name='clientes_id_nego_793ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['negocio', 'dni'], name='clientes_id_nego_d1a09e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['negocio', 'activo'], name='clientes_id_nego_feefe9_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientes',
            constraint=models.UniqueConstraint(fields=('negocio', 'dni'), name='uniq_cliente_dni_por_negocio'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['negocio', 'nombre'], name='categorias_id_nego_524d3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('negocio', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['negocio', 'descripcion'], name='productos_id_nego_6d6caf_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['negocio', 'categoria'], name='productos_id_nego_d97797_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['negocio', 'marca'], name='productos_id_nego_019a75_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['negocio', 'activo'], name='productos_id_nego_0f4bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['negocio', 'codigo_barra'], name='productos_id_nego_07f697_idx'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('precio_compra__gte', 0)), name='chk_precio_compra_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', 0)), name='chk_precio_venta_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='chk_stock_actual_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='chk_stock_minimo_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('margen_ganancia__isnull', True), models.Q(('margen_ganancia__gte', 0), ('margen_ganancia__lte', 100)), _connector='OR'), name='chk_margen_0_100'),
        ),
        migrations.AlterUniqueTogether(
            name='productos',
            unique_together={('negocio', 'codigo_barra'), ('negocio', 'sku')},
        ),
        migrations.AddIndex(
            model_name='respaldosistema',
            index=models.Index(fields=['fecha_respaldo'], name='respaldos_s_fecha_r_2405b9_idx'),
        ),
        migrations.AddIndex(
            model_name='respaldosistema',
            index=models.Index(fields=['usuario'], name='respaldos_s_usuario_166f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesistema',
            index=models.Index(fields=['tipo'], name='reportes_si_tipo_88d1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesistema',
            index=models.Index(fields=['negocio'], name='reportes_si_negocio_0686b2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesistema',
            index=models.Index(fields=['usuario'], name='reportes_si_usuario_313055_idx'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['negocio', 'fecha'], name='compras_id_nego_4a5f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['negocio', 'proveedor'], name='compras_id_nego_3fea21_idx'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['estado'], name='compras_estado_9eba4f_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacorasistema',
            index=models.Index(fields=['fecha'], name='bitacora_si_fecha_a40403_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacorasistema',
            index=models.Index(fields=['usuario'], name='bitacora_si_usuario_80fdc0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasistema',
            index=models.Index(fields=['tipo'], name='alertas_sis_tipo_64a451_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasistema',
            index=models.Index(fields=['nivel'], name='alertas_sis_nivel_db5522_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasistema',
            index=models.Index(fields=['estado'], name='alertas_sis_estado_8cad6d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasistema',
            index=models.Index(fields=['negocio'], name='alertas_sis_negocio_9cf4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['negocio', 'fecha'], name='ventas_id_nego_c57e00_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['negocio', 'estado'], name='ventas_id_nego_9328fd_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['negocio', 'anio', 'nro_secuencial'], name='ventas_id_nego_a3bae1_idx'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('negocio', 'anio', 'nro_secuencial'), name='uniq_venta_num_por_negocio_y_anio'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['venta'], name='detalle_ven_id_vent_d54f22_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['producto'], name='detalle_ven_id_prod_10cff5_idx'),
        ),
        migrations.AddIndex(
            model_name='ventapago',
            index=models.Index(fields=['venta'], name='pago_ventas_id_vent_cbcb65_idx'),
        ),
        migrations.AddIndex(
            model_name='ventapago',
            index=models.Index(fields=['metodo'], name='pago_ventas_metodo_ffcf22_idx'),
        ),
    ]
