# Generated by Django 5.2.15 on 2026-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AthenasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('ARQUEO', 'Arqueo')], max_length=10),
        ),
    ]
